database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  name:
  username:
  password:
  charset: utf8

rcon:
  host: localhost
  port: 27020
  password:

web:
  displayErrorDetails: false
  routerCacheFile: false

log_interval: 3
password:
debug: false
cache: ./cache
